config/routes.rb
Rails.application.routes.draw do
  get 'ruby_tutorial/index'

  get 'ruby_tutorial/introduction'

  get 'ruby_tutorial/installation'

  get 'ruby_tutorial/first_program'

  get 'ruby_tutorial/features'

  get 'ruby_tutorial/numbers'

  get 'ruby_tutorial/strings'

  get 'ruby_tutorial/variables'

  get 'ruby_tutorial/summary_1'

  get 'ruby_tutorial/scopes'

  get 'ruby_tutorial/getting_inputs'

  get 'ruby_tutorial/names'

  get 'ruby_tutorial/methods'

  get 'ruby_tutorial/summary_2'

  get 'ruby_tutorial/ruby_ri_tool'

  get 'ruby_tutorial/more_on_strings'

  get 'ruby3arabi/welcome'

  get 'ruby3arabi/about'

  get 'ruby3arabi/try_ruby'

  get 'ruby3arabi/privacy'

  root 'ruby3arabi#welcome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ruby3arabi_controller.rb
# encoding: utf-8

class Ruby3arabiController < ApplicationController
  def welcome
    @title = "روبي عربي | الرئيسية"
    @active_tap = "welcome"
  end

  def about
    @title = "روبي عربي | عن روبي عربي"
    @active_tap = "about"

    @list = [["about-satish.jpg","Satish Talim"],
             ["about-tno.jpg","محمد صبحي"],
             ["about-anyone.jpg","أيمن جاب الله"],
             ["about-sohail.jpg","سهيل نجم"],
             ["about-awam.jpg","عوام عبد النبي"]]
    @sort_list = [0, 1, 2, 3, 4].sample(5)
  end

  def privacy
    @title = "روبي عربي | سياسة الخصوصية"
  end

  def try_ruby
    @title = "روبي عربي | جرب روبي"
    @active_tap = "try_ruby"
  end
end

app/controllers/ruby_tutorial_controller.rb
# encoding: utf-8

class RubyTutorialController < ApplicationController
  def index
    @title = "دروس روبي | فهرس دروس روبي"
    @active_tap = "ruby_tutorial"
  end

  def introduction
    @title = "دروس روبي | المقدمة"
    @active_tap = "ruby_tutorial"
  end

  def installation
    @title = "دروس روبي | التنصيب"
    @active_tap = "ruby_tutorial"
  end

  def first_program
    @title = "دروس روبي | برنامجك الاول"
    @active_tap = "ruby_tutorial"
  end

  def features
    @title = "دروس روبي | مميزات روبي"
    @active_tap = "ruby_tutorial"
  end

  def numbers
    @title = "دروس روبي | الأعداد"
    @active_tap = "ruby_tutorial"
  end

  def strings
    @title = "دروس روبي | النصوص في روبي"
    @active_tap = "ruby_tutorial"
  end

  def variables
    @title = "دروس روبي | المتغيرات"
    @active_tap = "ruby_tutorial"
  end

  def summary_1
    @title = "دروس روبي | الملخص الأول"
    @active_tap = "ruby_tutorial"
  end

  def scopes
    @title = "دروس روبي | المجالات"
    @active_tap = "ruby_tutorial"
  end

  def getting_inputs
    @title = "دروس روبي | الحصول على المدخلات"
    @active_tap = "ruby_tutorial"
  end

  def names
    @title = "دروس روبي | الأسماء"
    @active_tap = "ruby_tutorial"
  end

  def methods
    @title = "دروس روبي | الطرق"
    @active_tap = "ruby_tutorial"
  end

  def summary_2
    @title = "دروس روبي | الملخص الثاني"
    @active_tap = "ruby_tutorial"
  end

  def ruby_ri_tool
    @title = "دروس روبي | روبي ri tool"
    @active_tap = "ruby_tutorial"
  end

  def more_on_strings
    @title = "دروس روبي | المزيد في النصوص"
    @active_tap = "ruby_tutorial"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_active_tap(controller_active_tap, view_active_tap)
    if controller_active_tap == view_active_tap
      true
    end
  end

  def markdown(text)
    render_options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow' }
    }
    renderer = CustomHtml.new(render_options)

    extensions = {
      autolink:           true,
      fenced_code_blocks: true,
      lax_spacing:        true,
      no_intra_emphasis:  true,
      strikethrough:      true,
      superscript:        true
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/ruby3arabi_helper.rb
module Ruby3arabiHelper
end

app/helpers/ruby_tutorial_helper.rb
module RubyTutorialHelper
end

app/views/ruby_tutorial/first_program.html.erb
<div class="panel panel-default beginning">
  <div class="panel-body">
    <p class="text-left">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <%= link_to "التنصيب", ruby_tutorial_installation_path, class: "btn btn-primary btn-sm" %>
      |
      <%= link_to "مميزات روبي", ruby_tutorial_features_path, class: "btn btn-primary btn-sm" %>
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </p>

    <h2 id="title">برنامجك الأول</h2>
    <p class="lead">برنامجك الأول على روبي</p>

    <p>بدايةً قم بفتح المحرر المفضل بالنسبة لك وقم بإعداده حسب رغبتك ، و الأن أنت مستعد لكتابة برنامجك الأول .</p>

    <p>يمكنك إنشاء مجلد تحت اسم <strong>برامج روبي</strong> وسنقوم بوضع كل برامجنا داخل هذا المجلد ، برنامجك الأول سيعرض جملة <strong class="font-Open-Sans-300">"!Hello World"</strong> على سطر أوامر ويندوز ( أو حسب نظام التشغيل الذي تعمل عليه ) .</p>

    <p>ملفات كود روبي تمتلك امتداد <strong class="font-Open-Sans-300">rb.</strong> ، أما على منصات ويندوز يمكن ان تنتهي بإمتداد <strong class="font-Open-Sans-300">rbw.</strong> ، على سبيل المثال <strong class="font-Open-Sans-300">myscript.rbw</strong> .</p>

    <p>أيضاً من المتعارف عليه عند تسمية ملفات كود روبي دائماً ما تكون بحروف صغيرة من اسم <strong class="font-Open-Sans-300">class/module</strong> ومثالاً لذلك عندما تمتلك <strong class="font-Open-Sans-300">class</strong> تحت اسم <strong class="font-Open-Sans-300">Foo</strong> يكون اسم الملف الذي يحتوي على الكود هو <strong class="font-Open-Sans-300">foo.rb</strong> .</p>

    <p class="set-margin-bottom-to-zero">قم بكتابة الكود التالي على محرر النصوص خاصتك .</p>
  </div>
</div>

<div class="panel panel-primary middle">
  <div class="panel-heading"><strong>p001.rb</strong></div>
  <div class="panel-body set-padding-to-zero">

    <div>
      <div class="syntaxhighlighter ruby">
        <table border="0" cellpadding="0" cellspacing="0">
          <tbody>
            <tr>
              <td class="gutter">
                <div class="line number1 index0 alt2">1</div>
              </td>

              <td class="code">
                <div class="container">
                  <div class="line number1 index0 alt2"><code class="ruby plain">puts</code> <code class="ruby string">'Hello World!'</code></div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

<div class="panel panel-default middle">
  <div class="panel-body">
    <p>بعد ذلك قم بحفظ الملف تحت اسم <strong class="font-Open-Sans-400">p001.rb</strong> داخل مجلد <strong>برامج روبي</strong> .</p>

    <p class="set-margin-bottom-to-zero">لتقوم بتشغيل الكود الذي كتبته الأن ، قم بفتح سطر الأوامر وقم بالتوجه إلى موقع حفظ الملف داخل مجلد برامج روبي و قم بكتابة <strong class="font-Open-Sans-400">ruby p001.rb</strong> ، يجب أن تشاهد الناتج كما هو موضح في الأسفل .</p>
  </div>
</div>

<div class="panel panel-primary middle">
  <div class="panel-heading text-right"><strong class="font-DroidKufi-Regular">ناتج التنفيذ</strong></div>
  <div class="panel-body set-padding-to-zero">

    <div>
      <div id="highlighter_460146" class="syntaxhighlighter bash">
        <table border="0" cellpadding="0" cellspacing="0">
          <tbody>
            <tr>
              <td class="gutter">
                <div class="line number1 index0 alt2">1</div>
                <div class="line number2 index1 alt1">2</div>
                <div class="line number3 index2 alt2">3</div>
                <div class="line number4 index3 alt1">4</div>
              </td>
              <td class="code">
                <div class="container">
                <div class="line number1 index0 alt2"><code class="bash plain">C:\برامج روبي&gt; ruby p001.rb</code></div>
                <div class="line number2 index1 alt1"><code class="bash plain">Hello World!</code></div>
                <div class="line number3 index2 alt2"> </div>
                <div class="line number4 index3 alt1"><code class="bash plain">C:\برامج روبي&gt;</code></div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

<div class="panel panel-default middle">
  <div class="panel-body">
    <p>كما لاحظتم روبي لغة سكربتات بمعنى انه لا يوجد دالة رئيسية - <strong class="font-Open-Sans-400">main method</strong> - يبدأ منها التنفيذ ، مفسر روبي يأخذ الكود و يبدأ بتنفيذه سطر بعد الأخر من أول سطر إلى أن يصل إلى أخر سطر .</p>

    <p class="set-margin-bottom-to-zero"><strong class="font-Open-Sans-400">puts</strong> هي دالة معرفة داخل اللغة تقوم بطباعة النص الذي يأتي بعدها على الشاشة وتقوم بالإنتقال إلى السطر التالي تلقائياً ، يمكنك إستخدام الدالة <strong class="font-Open-Sans-400">print</strong> بدلاً منها ولكنها لن تنتقل إلى السطر الذي بعده هذا هو الفرق بينهما ( الدالة <strong class="font-Open-Sans-300">puts</strong> أكثر إستخداماً من <strong class="font-Open-Sans-300">print</strong> ) .</p>
  </div>
</div>

<div class="panel panel-primary middle">
  <div class="panel-heading"><strong>p002.rb</strong></div>
  <div class="panel-body set-padding-to-zero">

    <div>
      <div class="syntaxhighlighter ruby">
        <table border="0" cellpadding="0" cellspacing="0">
          <tbody>
            <tr>
              <td class="gutter">
                <div class="line number1 index0 alt2">1</div>
              </td>

              <td class="code">
                <div class="container">
                  <div class="line number1 index0 alt2"><code class="ruby plain">print</code> <code class="ruby string">'Hello World!'</code></div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

<div class="panel panel-primary middle">
  <div class="panel-heading text-right"><strong class="font-DroidKufi-Regular">ناتج التنفيذ</strong></div>
  <div class="panel-body set-padding-to-zero">

    <div>
      <div id="highlighter_460146" class="syntaxhighlighter bash">
        <table border="0" cellpadding="0" cellspacing="0">
          <tbody>
            <tr>
              <td class="gutter">
                <div class="line number1 index0 alt2">1</div>
                <div class="line number2 index1 alt1">2</div>
                <div class="line number3 index2 alt2">3</div>
              </td>
              <td class="code">
                <div class="container">
                <div class="line number1 index0 alt2"><code class="bash plain">C:\برامج روبي&gt; ruby p002.rb</code></div>
                <div class="line number2 index1 alt1"><code class="bash plain">Hello World!</code></div>
                <div class="line number3 index2 alt2"><code class="bash plain">C:\برامج روبي&gt;</code></div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

<div class="panel panel-default middle">
  <div class="panel-body">
    <p>أتمنى أنك لاحظت الفارق بين المثال الأول و الثاني حيث أنه في المثال الأول بعد طباعة النص قام بترك سطر فارغ و سمح لك بكتابة باقي الأوامر أما في المثال الثاني لم يترك لك أي فراغ و سمح لك بمتابعة الكتابة بعد النص مباشرة .</p>

    <p class="set-margin-bottom-to-zero">يمكنك الفهم أكثر إذا قمنا بتشغيل البرنامج <strong class="font-Open-Sans-400">p002.rb</strong> .</p>
  </div>
</div>

<div class="panel panel-danger middle">
  <div class="panel-heading">ملاحظة</div>
  <div class="panel-body">
    <p>أ - أثناء الحديث عن الدالتين <strong class="font-Open-Sans-300">puts , print</strong> لم نقم بكتابة أي أقواس أثناء الإستدعاء ، في الحقيقة هي إختيارية في لغة روبي أثناء إستدعاء أي دالة كانت سواء تحتوي على متغيرات أم لا ، للإيضاح أكثر كل الإستدعاءات التالية صحيحة :</p>

    <p class="set-direction-ltr">
      <strong class="font-Open-Sans-300">
        foobar <br>
        foobar() <br>
        foobar(a, b, c) <br>
        foobar a, b, c
      </strong>
    </p>

    <p>ب - في روبي كل شيء بدايةً من الأعداد الصحيحة وصولاً إلى النصوص هي كائنات - <strong class="font-Open-Sans-400">objects</strong> - وكل كائن يحتوي داخله على دوال جاهزة يمكن إستخدامها في أغراض متعددة . لتتمكن من إستخدام الدالة يجب عليك وضع <strong>نقطة</strong> بعد الكائن الذي تريد تطبيق الدالة عليه بعد ذلك تقوم بكتابة اسم الدالة المراد استخدامها . بعض الدوال مثل <strong class="font-Open-Sans-300">puts , print</strong> يمكن استخدامها في أي مكان دون الحاجة لإسنادها إلى متغير معين .</p>

    <p class="set-margin-bottom-to-zero">بعمق أكثر ، هذه الدوال تم تجهيزها مسبقاً من قبل اللغة داخل <strong class="font-Open-Sans-300"><span class="font-Open-Sans-400">Kernal</span> module</strong> و تم إحتوائها في جميع كائنات روبي ( <strong class="font-Open-Sans-300"><span class="font-Open-Sans-400">Kernal</span> module</strong> تم إحتوائها من قبل <strong class="font-Open-Sans-300"><span class="font-Open-Sans-400">Object</span> class</strong> ، لذلك كل هذه الدوال تلقائياً متاحة في كل كائنات روبي ) وعندما تقوم بتشغيل برنامج روبي ، الكائن يقوم بإستدعاء <strong class="font-Open-Sans-400">main</strong> من <strong class="font-Open-Sans-400">Object</strong> عند الإنشاء ، وهذا الكائن سيحتوي تلقائياً على كل دوال <strong class="font-Open-Sans-400">Kernal</strong> .</p>
  </div>
</div>

<div class="panel panel-default last">
  <div class="panel-body">
    <p class="lead">لاحظ أن :</p>

    <ol class="lists">
      <li>بالنسبة لمبرمجي لغات مثل <strong class="font-Open-Sans-300">Java , C</strong> لا حاجة لأن تقوموا بتعريف دالة رئيسية ( <strong class="font-Open-Sans-300">main method/function</strong> ) .</li>
      <li>النصوص في روبي يمكن كتابتها داخل علامة إقتباس أحادية ' أو ثنائية " ، خلال الأمثلة السابقة قمت بإستخدام العلامة الأحادية فهي أكثر كفاءة من الثنائية ( سنتعرف على هذا فيما بعد ) .</li>
      <li>روبي لغة مفسرة لذا لا حاجة للقيام بإعادة ترجمة للكود الخاص بك كي يعمل على منصة أو بنية مختلفة عن الذي قمت بتصميم برنامجك عليها .</li>
      <li>من المتعارف عليه عند تسمية ملفات كود روبي دائماً ما تكون بحروف صغيرة من اسم <strong class="font-Open-Sans-300">class/module</strong> ومثالاً لذلك عندما تمتلك <strong class="font-Open-Sans-300">class</strong> تحت اسم <strong class="font-Open-Sans-300">Foo</strong> يكون اسم الملف الذي يحتوي على الكود هو <strong class="font-Open-Sans-300">foo.rb</strong> .</li>
    </ol>

    <p class="set-margin-bottom-to-zero text-left">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <%= link_to "التنصيب", ruby_tutorial_installation_path, class: "btn btn-primary btn-sm" %>
      |
      <%= link_to "مميزات روبي", ruby_tutorial_features_path, class: "btn btn-primary btn-sm" %>
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </p>
  </div>
</div>

app/views/ruby_tutorial/getting_input.html.erb
<div class="panel panel-default beginning">
  <div class="panel-body">
    <p class="text-left">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <%= link_to "المجالات", ruby_tutorial_scope_path, class: "btn btn-primary btn-sm" %>
      |
      <%= link_to "الأسماء", ruby_tutorial_names_path, class: "btn btn-primary btn-sm" %>
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </p>

    <h2 id="title">الحصول على المدخلات</h2>

    <p class="set-margin-bottom-to-zero">في دروسنا السابقة تعاملنا فقط مع المخرجات و طباعة بعض الجمل و الكلكمات على الشاشة ، لكن كيف يمكن لنا أن نستقبل المدخلات من المستخدم ؟ ، لفعل ذلك نستخدم الدالة <strong class="font-Open-Sans-400">gets</strong> أيضاً سنستخدم معها <strong class="font-Open-Sans-400">chomp</strong> ، البرنامج التالي يوضح كيفية إستخدام الدوال المذكورة .</p>
  </div>
</div>

<div class="panel panel-primary middle">
  <div class="panel-heading"><strong>p012.rb</strong></div>
  <div class="panel-body set-padding-to-zero">

    <div>
      <div id="highlighter_862157" class="syntaxhighlighter ruby">
        <table border="0" cellpadding="0" cellspacing="0">
          <tbody>
            <tr>
              <td class="gutter">
                <div class="line number1 index0 alt2">1</div>
                <div class="line number2 index1 alt1">2</div>
                <div class="line number3 index2 alt2">3</div>
              </td>
              <td class="code">
                <div class="container">
                  <div class="line number1 index0 alt2"><code class="ruby plain">puts </code><code class="ruby string">"In which city do you stay ?"</code></div>
                  <div class="line number2 index1 alt1"><code class="ruby plain">city = gets.chomp</code></div>
                  <div class="line number3 index2 alt2"><code class="ruby plain">puts </code><code class="ruby string">"The city is "</code> <code class="ruby plain">+ city</code></div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

<div class="panel panel-primary middle">
  <div class="panel-heading text-right"><strong class="font-DroidKufi-Regular">ناتج التنفيذ</strong></div>
  <div class="panel-body set-padding-to-zero">

    <div>
      <div id="highlighter_316670" class="syntaxhighlighter bash">
        <table border="0" cellpadding="0" cellspacing="0">
          <tbody>
            <tr>
              <td class="gutter">
                <div class="line number1 index0 alt2">1</div>
                <div class="line number2 index1 alt1">2</div>
                <div class="line number3 index2 alt2">3</div>
                <div class="line number4 index3 alt1">4</div>
                <div class="line number5 index4 alt2">5</div>
                <div class="line number6 index5 alt1">6</div>
              </td>
              <td class="code">
                <div class="container">
                  <div class="line number1 index0 alt2"><code class="bash plain">C:\برامج روبي&gt; ruby p012.rb</code></div>
                  <div class="line number2 index1 alt1"><code class="bash plain">In which city do you stay ?</code></div>
                  <div class="line number3 index2 alt2"><code class="bash plain">Benghazi</code></div>
                  <div class="line number4 index3 alt1"><code class="bash plain">The city is Benghazi</code></div>
                  <div class="line number5 index4 alt2">&nbsp;</div>
                  <div class="line number6 index5 alt1"><code class="bash plain">C:\برامج روبي&gt;</code></div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

<div class="panel panel-default last">
  <div class="panel-body">
    <p>وكما إعتدنا بعد كل برنامج بعد أن نقوم بتنفيذه نبدأ في شرحه ، بدايةً سألنا المستخدم عن المدينة التي يعيش فيها و إنتظرنا منه أن يقوم بكتابة اسم المدينة ، قمنا بتعريف متغير و كانت قيمة المتغير تساوي الدالة <strong class="font-Open-Sans-400">gets</strong> والتي توقف تنفيذ البرنامج و تنتظر مدخلات على سطر واحد من المستخدم ، و قمنا بإستدعاء الطريقة <strong class="font-Open-Sans-400">chomp</strong> ليتم تنفيذها على المدخلات التي سيتم إرجاعها من الدالة <strong class="font-Open-Sans-400">gets</strong> ، بعد ذلك يتم تعيين هذه المدخلات إلى المتغير <strong class="font-Open-Sans-400">city</strong> ، طبعاً في حالتنا هذه يتسائل البعض عن ما هي العناصر القياسية التي يتم الإدخال منها ، هذا الأمر يتعلق بنظام التشغيل ، فكل نظام تشغيل قام بتعريف عنصر قياسي ليتم التعامل معه وإستقبال المدخلات منه ، وفي حالتنا هذا العنصر هو لوحة المفاتيح ، وفي النهاية نقوم بطباعة جملة نقول فيها "المدينة هي ..." حسب المدخلات التي تم إستقبالها .</p>

    <p>نأتي الأن لنشرح إستعمال او فائدة الطريقة <strong class="font-Open-Sans-400">chomp</strong> التي إستخدمناها في البرنامج السابق ، هذه الطريقة تستقبل سلسلة حرفية كمدخلات ، عند إستقبال أي مدخل فإننا نستقبله على هيئة سلسلة نصية تنتهي بسطر جديد ، فنحن نستخدم الطريقة <strong class="font-Open-Sans-400">chomp</strong> لنقوم بإزالة هذا السطر و طباعة المدخل بشكل أفضل .</p>

    <p class="text-left set-margin-bottom-to-zero">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <%= link_to "المجالات", ruby_tutorial_scope_path, class: "btn btn-primary btn-sm" %>
      |
      <%= link_to "الأسماء", ruby_tutorial_names_path, class: "btn btn-primary btn-sm" %>
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </p>
  </div>
</div>

app/views/ruby_tutorial/index.html.erb
<div class="panel panel-default alone">
  <div class="panel-body">
    <h1 id="title">فهرس دروس روبي</h1>

    <ul class="set-margin-bottom-to-zero lists">
      <li><strong><%= link_to "المقدمة", ruby_tutorial_introduction_path, class: "index-link" %></strong></li>
      <li><strong><%= link_to "التنصيب", ruby_tutorial_installation_path, class: "index-link" %></strong>
        <ul>
          <li>ما هي روبي ؟</li>
          <li>تنزيل روبي</li>
        </ul>
      </li>
      <li><strong><%= link_to "برنامجك الاول", ruby_tutorial_first_program_path, class: "index-link" %></strong></li>
      <li><strong><%= link_to "مميزات روبي", ruby_tutorial_features_path, class: "index-link" %></strong></li>
      <li><strong><%= link_to "الأعداد", ruby_tutorial_numbers_path, class: "index-link" %></strong>
        <ul>
          <li>العمليات</li>
          <li>الفرق بين العملية <strong class="font-Open-Sans-300">or</strong> و ||</li>
        </ul>
      </li>
      <li><strong><%= link_to "النصوص في روبي", ruby_tutorial_strings_path, class: "index-link" %></strong></li>
      <li><strong><%= link_to "المتغيرات", ruby_tutorial_variables_path, class: "index-link" %></strong></li>
      <li><strong><%= link_to "الملخص الأول", ruby_tutorial_summary_1_path, class: "index-link" %> <sup><span class="glyphicon glyphicon-star" aria-hidden="true" style="color: #BD110A;"></span></sup></strong></li>
      <li><strong><%= link_to "المجالات", ruby_tutorial_scopes_path, class: "index-link" %></strong>
        <ul>
          <li>النطاق العام و المتغيرات العامة</li>
          <li>المتغيرات العامة المضمنة</li>
          <li>النطاق المحلي</li>
        </ul>
      </li>
      <li><strong><%= link_to "الحصول على المدخلات", ruby_tutorial_getting_inputs_path, class: "index-link" %></strong></li>
      <li><strong><%= link_to "الأسماء", ruby_tutorial_names_path, class: "index-link" %></strong></li>
      <li><strong><%= link_to "الطرق", ruby_tutorial_methods_path, class: "index-link" %></strong>
        <ul>
          <li>طرق العلامة (!)</li>
          <li>الطرق التي تنتهي بـ (؟)</li>
        </ul>
      </li>
      <li><strong><%= link_to "الملخص الثاني", ruby_tutorial_summary_2_path, class: "index-link" %> <sup><span class="glyphicon glyphicon-star" aria-hidden="true" style="color: #BD110A;"></span></sup></strong></li>
      <li><strong><%= link_to sanitize('روبي <strong class="font-Open-Sans-400">ri tool</strong>'), ruby_tutorial_ruby_ri_tool_path, class: "index-link" %></strong></li>
      <li><strong><%= link_to "المزيد في النصوص", ruby_tutorial_more_on_strings_path, class: "index-link" %></strong>
        <ul>
          <li>سرد كافة طرق فئة أو كائن</li>
          <li>المقارنة بين النصوص</li>
          <li>إسنخدام <strong class="font-Open-Sans-300">%w</strong></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/ruby_tutorial/ruby_ri_tool.html.erb
<div class="panel panel-default beginning">
  <div class="panel-body">
    <p class="text-left">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <%= link_to "الملخص الثاني", ruby_tutorial_summary_2_path, class: "btn btn-primary btn-sm" %>
      |
      <%= link_to "المزيد في النصوص", ruby_tutorial_more_on_strings_path, class: "btn btn-primary btn-sm" %>
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </p>

    <h2 id="title">روبي <strong class="font-Open-Sans-400">ri tool</strong></h2>

    <p></p>
  </div>
</div>